In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
## Define the vocabulary size
voc_size=10000

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3863, 1857, 1133, 3405],
 [3863, 1857, 1133, 8148],
 [3863, 1793, 1133, 2526],
 [8363, 1506, 3391, 8556, 8152],
 [8363, 1506, 3391, 8556, 5813],
 [6126, 3863, 3201, 1133, 963],
 [5331, 2347, 8922, 8556]]

In [11]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3863 1857 1133 3405]
 [   0    0    0    0 3863 1857 1133 8148]
 [   0    0    0    0 3863 1793 1133 2526]
 [   0    0    0 8363 1506 3391 8556 8152]
 [   0    0    0 8363 1506 3391 8556 5813]
 [   0    0    0 6126 3863 3201 1133  963]
 [   0    0    0    0 5331 2347 8922 8556]]


In [14]:
## feature representation
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 98ms/step


array([[[ 0.01238841,  0.04691497, -0.03435173, -0.02939299,
         -0.03442379,  0.04607941, -0.01464546,  0.00836368,
         -0.00196449,  0.02393366],
        [ 0.01238841,  0.04691497, -0.03435173, -0.02939299,
         -0.03442379,  0.04607941, -0.01464546,  0.00836368,
         -0.00196449,  0.02393366],
        [ 0.01238841,  0.04691497, -0.03435173, -0.02939299,
         -0.03442379,  0.04607941, -0.01464546,  0.00836368,
         -0.00196449,  0.02393366],
        [ 0.01238841,  0.04691497, -0.03435173, -0.02939299,
         -0.03442379,  0.04607941, -0.01464546,  0.00836368,
         -0.00196449,  0.02393366],
        [-0.00247778, -0.02100906,  0.02934447, -0.01977136,
          0.01426597,  0.01150237,  0.01939761,  0.03708068,
          0.02305656, -0.02002093],
        [ 0.03496296, -0.00750697,  0.02633187, -0.02921191,
          0.04785179,  0.01586458, -0.00821001,  0.01687947,
         -0.03119098,  0.0149383 ],
        [-0.00129613,  0.00367016,  0.03278463, -0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 3863, 1857, 1133, 3405])

In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 47ms/step


array([[ 0.01238841,  0.04691497, -0.03435173, -0.02939299, -0.03442379,
         0.04607941, -0.01464546,  0.00836368, -0.00196449,  0.02393366],
       [ 0.01238841,  0.04691497, -0.03435173, -0.02939299, -0.03442379,
         0.04607941, -0.01464546,  0.00836368, -0.00196449,  0.02393366],
       [ 0.01238841,  0.04691497, -0.03435173, -0.02939299, -0.03442379,
         0.04607941, -0.01464546,  0.00836368, -0.00196449,  0.02393366],
       [ 0.01238841,  0.04691497, -0.03435173, -0.02939299, -0.03442379,
         0.04607941, -0.01464546,  0.00836368, -0.00196449,  0.02393366],
       [-0.00247778, -0.02100906,  0.02934447, -0.01977136,  0.01426597,
         0.01150237,  0.01939761,  0.03708068,  0.02305656, -0.02002093],
       [ 0.03496296, -0.00750697,  0.02633187, -0.02921191,  0.04785179,
         0.01586458, -0.00821001,  0.01687947, -0.03119098,  0.0149383 ],
       [-0.00129613,  0.00367016,  0.03278463, -0.01783981,  0.03760831,
         0.02677603,  0.02284683, -0.01646604